# Generated by Django 5.0.6 on 2024-06-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_member_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('1', 'Founder'), ('2', 'Manager'), ('3', 'Convener')], default=None, max_length=100),
        ),
    ]
